services:
  farmland-api:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api
    depends_on:
       - db
    ports:
      - "8000:8000"

  db:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecret
